controller:
  service:
    loadBalancerIP: 10.186.28.100
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
1
kind: Service
metadata:
  name: lb-k8s-internal
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-aks"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.186.28.100
  ports:
  - port: 80
  selector:
    app: lb-k8s-internal
2
apiVersion: v1
kind: Service
metadata:
  name: lb-k8s-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.25
  ports:
  - port: 80
  selector:
    app: lb-k8s-internal